### ISSUE TITLE
Cannot install on macos: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by mhstnsc** [google-research/recsim#9]
After following the installation instructions. 
I used pip3 as python2 was failing to install the atari lib.
I also upgraded dopamine.

I am running in an python3.7 virtual env 

```
Successfully installed Pillow-6.2.1 dopamine-rl-3.0.1
mhstnsc-mac:~/personal/recsim/recsim [master ?] $ ./start.sh
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    from recsim.agents import full_slate_q_agent
  File "/usr/local/lib/python3.7/site-packages/recsim/agents/__init__.py", line 19, in <module>
    from recsim.agents import full_slate_q_agent
  File "/usr/local/lib/python3.7/site-packages/recsim/agents/full_slate_q_agent.py", line 22, in <module>
    from recsim.agents.dopamine import dqn_agent
  File "/usr/local/lib/python3.7/site-packages/recsim/agents/dopamine/dqn_agent.py", line 23, in <module>
    from dopamine.agents.dqn import dqn_agent
  File "/usr/local/lib/python3.7/site-packages/dopamine/agents/dqn/dqn_agent.py", line 27, in <module>
    from dopamine.discrete_domains import atari_lib
  File "/usr/local/lib/python3.7/site-packages/dopamine/discrete_domains/atari_lib.py", line 54, in <module>
    from tensorflow.contrib import layers as contrib_layers
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by cwhsu-google** [comment]
Thank you for using RecSim. What is the version of tensorflow? Could you try tensorflow 1.15 as said in
https://github.com/google/dopamine/blob/master/README.md#mac-os-x

**Comment by mhstnsc** [comment]
this will probsbly work, thx, closing this not to leave stuff open
